repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev:  v0.15.5  
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 26.1.0  
    hooks:
      - id: black
        language_version: python3.14
        
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c "cd DSA_Dice && poetry run pytest"
        language: system
        pass_filenames: false
        working_dir: DSA_Dice




